### PR TITLE
Add missing endpoints in RecurlyClient

### LINKED ISSUE #251: Missing function to get all available Invoices
Hi I'm using version `0.14.0` and seems that there is not a function in order to fetch all available Invoices directly from Recurly without iterating through all existing accounts.

Reference: https://dev.recurly.com/docs/list-invoices

### LINKED ISSUE #253: Unable to Update Shipping Address
The RecurlyClient class does not provide a way to update the Shipping Address for an account. There is an HTTP API 
`PUT .../accounts/:account_code/shipping_addresses/:shipping_address_id` 
to update the shipping address, but not in Java library. As an alternative, I tried to change the shipping address with HTTP PUT .../accounts/{accountId}) and provided the the shipping address in the request payload, but I received
 `<error>
    <symbol>invalid_xml</symbol>
    <description>The provided XML was invalid.</description>
    <details>You can only nest shipping_addresses in your XML when creating a new record, not when updating.</details>
</error>`

The library does not appear to support the Delete Shipping Address feature either.
Is there an alternative that I'm missing?

### PR DESCRIPTION
**Pull request by bhelx**
Resolves #251 
Adds missing endpoints for site-wide invoices

Resolves #253 
Adds missing Shipping Address endpoints

### CODE REVIEW

**Comment by MiellyEllen** [comment]
Thanks @bhelx The PR looks good. Are you looking for my approval? We really need this feature.  Do you know when a release will be available?

**Comment by bhelx** [comment]
@MiellyEllen do you have a way to verify it? If so, that would be helpful. Otherwise, I'll get it merged today and it will go out in the next release. 

\cc @pierre do you have time to perform a release after this PR goes in?

**Comment by MiellyEllen** [comment]
@bhelx , other than looking at the code, no I'm not able to verify it.

**Comment by bhelx** [comment]
@MiellyEllen No problem. I ran some tests and made an integration test so I think it's good.

**Comment by pierre** [comment]
> @pierre do you have time to perform a release after this PR goes in?

Sure thing @bhelx! 0.16.0 released.

**Comment by bhelx** [comment]
thanks @pierre !

**Pull request merged**
