### PR TITLE
Mapped tax fields from recurly to account, invoice and subscription

### PR DESCRIPTION
**Pull request by mzouitni**

### CODE REVIEW

**Comment by mzouitni** [comment]
I started with a brand new PR. Let me know if there is anything that needs to be fixed. If everything is good to go how soon can we publish a new release to maven repo?

**Comment by bhelx** [comment]
@mzouitni looks good! Thanks a lot for your persistence on this. Just ran the tests and they all pass :+1:

**Comment by mzouitni** [comment]
I am glad it is in. @pierre when do you think this will make it into maven repo?

**Comment by pierre** [comment]
Probably soon - I'd like for us to do a pass at all the open PRs first.

**Comment by mzouitni** [comment]
@pierre do you have an ETA? I need to know when we can incorporate these changes in our code.

**Comment by pierre** [comment]
No ETA - hopefully end of week.

**Comment by mzouitni** [comment]
@pierre thank you!

**Comment by mzouitni** [comment]
@pierre Any updates on cutting a release and pushing it to maven repo? We are towards the end of our release and we need these changes asap. Thank you!

**Comment by pierre** [comment]
[0.6.2](https://search.maven.org/#artifactdetails%7Ccom.ning.billing%7Crecurly-java-library%7C0.6.2%7Cjar) is now available.

**Comment by mzouitni** [comment]
Thank you!!

**Pull request merged**
