### PR TITLE
Update generateUniqueCodes to return coupons

### PR DESCRIPTION
**Pull request by joannasese**
- Update `generateUniqueCodes()` to return array of coupons (e.g. return object `coupons`: `coupons.get(0).getCouponCode()` yields `whatevercode123`
- Alter `callRecurlyXmlContent()` to return coupons when `clazz == Coupons.class`

```java
Coupon genCouponData = new Coupon();
genCouponData.setNumberOfUniqueCodes(3);
Coupons coupons = recurlyClient.generateUniqueCodes(coupon.getCouponCode(), genCouponData);
Coupon c = coupons.get(0);
System.out.println("Coupon c " + c.toString());
```

### CODE REVIEW

**Comment by cyu521** [comment]
thanks @joannasese for the quick reply and getting this pr up so fast!

when this gets merge, can a new version of this lib be build so I can pull it?

Thanks!

**Comment by joannasese** [comment]
@cyu521 no problem! 

Just wanted to double check - this works for us but can you confirm that it's working for you, too?

**Comment by cyu521** [comment]
@joannasese since im just importing the libs and not the actual source code, I did not get to test this on my end. if this works for you, i dont see a reason why it wouldn't work on my end.

**Comment by joannasese** [comment]
@pierre when you have a free moment, would you mind publishing a release? thank you in advance.

**Comment by pierre** [comment]
`0.31.0` released!

**Pull request merged**
