### PR TITLE
coupon: fix plan_codes parsing

### PR DESCRIPTION
**Pull request by pierre**
This fixes https://github.com/killbilling/recurly-java-library/issues/244.

Any idea for the `must_apply_to_plans_or_non_plan_charges` error on Travis?

### CODE REVIEW

**Comment by aaron-suarez** [comment]
This is an example of the XML being sent by `createCoupon`

```xml
<coupon xmlns=""><name>yzEBnzLFk3</name><coupon_code>yzebnzlfk3</coupon_code><applies_to_all_plans>false</applies_to_all_plans><discount_type>percent</discount_type><discount_percent>61</discount_percent><plan_codes><plan_code></plan_code></plan_codes></coupon>
```
Notice at the very end that it does not contain the plan_code in `<plan_codes><plan_code></plan_code></plan_codes>`

I'll look into it a little farther later if you don't get to it by then, but I suspect that `couponDataForPlan.setPlanCodes(planCodes);` is not successfully setting the plan code, or that there's something wrong with the serialization.

**Comment by pierre** [comment]
@aaron-suarez Should be fixed! 😅

**Comment by bhelx** [comment]
If it works, let's merge it! Fixing the general case problem seemed like a rabbit-hole to me and I think we should provide some relief on this problem for the time being.

**Comment by bhelx** [comment]
Thanks @pierre !

**Pull request merged**
