### PR TITLE
Run integration tests on travis

### PR DESCRIPTION
**Pull request by bhelx**
https://github.com/killbilling/recurly-java-library/issues/71

Have travis run the integration tests against a recurly sandbox account

### CODE REVIEW

**Comment by pierre** [comment]
I can setup a private environment variable in Travis if you prefer hiding the key?

**Comment by bhelx** [comment]
@pierre I created a sandbox site and set it up with the following:

1. Disable Line-Item Refunds (need to do this to make the integration tests pass but we can fix this later)
2. Enabled multiple coupn redemptions per account in coupon settings

I added the key directly into the travis file for now. Let me know how we can change it to use travis environment variables and i can revoke that key.

**Comment by pierre** [comment]
> Let me know how we can change it to use travis environment variables and i can revoke that key.

Can you email me the new key? I'll set it up.

**Comment by bhelx** [comment]
Sure thing

**Comment by pierre** [comment]
Thanks!

I've configured the environment variables $API_KEY and $SUBDOMAIN.

**Comment by bhelx** [comment]
@pierre okay updated. Seems to be working!

**Comment by bhelx** [comment]
Old key revoked

**Comment by pierre** [comment]
:tada: Sweet! :tada:

**Comment by bhelx** [comment]
I'm going to leave myself a recurring calendar appointment to clear out the test site. I'll see if there is a better way to deal with it in the future. It might be time to add that "clear sandbox site" feature to the api.

**Pull request merged**
