### PR TITLE
Replace uses of Guava's Objects#firstNonNull with MoreObjects#firstNonNull 

### LINKED ISSUE #171: Replace uses of Guava's Objects#firstNonNull with MoreObjects#firstNonNull
I tried to use Guava v.21 in our application and got a runtime error because RecurlyClient.java uses  com.google.common.base.Objects#firstNonNull (which was removed Guava 21). This method was deprecated in v.18 and it is recommended to use com.google.common.base.MoreObjects#firstNonNull instead. Thank you!

### PR DESCRIPTION
**Pull request by bhelx**
Resolves #171

### CODE REVIEW

**Comment by bhelx** [comment]
@pierre are there any implications to this for people who may be using an older version?

**Comment by cfrasineanu-intx** [comment]
Guava 21 requires Java 8

**Comment by bhelx** [comment]
@cfrasineanu-intx thanks, I did not notice this. Perhaps just switching to using `MoreObjects` is enough for right now.

**Comment by cfrasineanu-intx** [comment]
enough for our project. Thanks

**Comment by pierre** [comment]
> @pierre are there any implications to this for people who may be using an older version?

Upgrading transitive dependencies is always tricky, especially for people using Guava in their project. We don't really know if they rely on a specific version, which could be incompatible with the version we need.

👍 for non upgrading, unless we have to.

**Pull request merged**
