### PR TITLE
Implements restore coupon

### PR DESCRIPTION
**Pull request by slisaasquatch**
Implements https://dev.recurly.com/docs/restore-coupon

### CODE REVIEW

**Comment by joannasese** [comment]
@slisaasquatch thanks again for your contribution. We'll take a look.

**Comment by joannasese** [comment]
Hi @slisaasquatch. Your implementation looks sound, but the restore coupon endpoint does not actually seem to function. Were you able to restore a coupon after expiring it? This might not be unique to the Java client library, so I'm going to keep this open for now while I test in other libraries.

**Comment by slisaasquatch** [comment]
Hi @joannasese , I am able to restore a coupon after *deleting* it. I have not tried restoring expired coupons.

**Comment by joannasese** [comment]
@slisaasquatch do you mind throwing up some sample code of how you're deleting and restoring?

**Comment by slisaasquatch** [comment]
For deleting the coupon, I simply used `recurlyClient.deleteCoupon(couponCode);`. And for restoring, I used `recurlyClient.restoreCoupon(couponCode, new Coupon())`.

**Comment by joannasese** [comment]
Ah perfect. I was running (almost) the same code, but with an embarrassing typo. Let's call it a case of the Fridays. 

```java
final Coupon coupon = new Coupon();
coupon.setCouponCode("blackfriday");
coupon.setName("Black Friday Coupon");
coupon.setDiscountType("percent");
coupon.setDiscountPercent(10);
client.createCoupon(coupon);
System.out.println("Coupon created: " + coupon.getCouponCode());

client.deleteCoupon(coupon.getCouponCode());

final Coupon coupon2 = new Coupon();
coupon2.setName("New Coupon Name");

client.restoreCoupon(coupon.getCouponCode(), coupon2); // instead of coupon2, I had typed coupon
System.out.println("Coupon Restored: " + coupon.getCouponCode());
```

I'll go ahead and get this merged. Thanks again for your contribution!

**Pull request merged**
