### PR TITLE
Ignore case of 'type' attribute of a Recurly object to fix deserializ…

### PR DESCRIPTION
**Pull request by lc-ikrumov**
…ation issue of 'dateTime' type

### CODE REVIEW

**Comment by mzouitni** [comment]
@pierre Any possibility of getting this merged in soon? My team is impacted by this issue as well. 
Thank you!

**Comment by pierre** [comment]
@mzouitni This is quite a large change -- I'd like @bhelx to review it first, he may have more insights into these behavior changes.

**Comment by mzouitni** [comment]
Any idea how long it might take to get an update?

**Comment by bhelx** [comment]
@lc-ikrumov @mzouitni 

Hey guys, I'm on vacation at the moment so won't be able to look at this in much detail. If the xml indeed changed then that's certainly a mistake on the side of the server. I've notified the team and they will take a look at it and update you here.

**Comment by mzouitni** [comment]
Thank you @bhelx. We have about 91 failed webhooks. Any possibility that they will be fixed if we retry them? All of them have the camel case date and the retries have been exhausted.

**Comment by bhelx** [comment]
@mzouitni if you contact our official support and let them know the recurly site and the time range in question, they can help you.

**Comment by mzouitni** [comment]
@bhelx We have reached out to support and they told that they have to escalate to Tier 3 support and haven't heard anything since yesterday.

**Comment by mattcarrier** [comment]
@bhelx @pierre @lc-ikrumov 

We have gone ahead and put this into production on our end.  I can vouch that this has resolved all the existing webhook problems that we had encountered.

**Comment by bhelx** [comment]
Thanks everyone for weighing in on this. As a general rule we do not make changes to webhooks that are not backwards compatible. So this was in fact a mistake and I don't foresee us making this kind of change again until we decide to version the webhooks.

Having said that, I think these comparisons should be case insensitive anyway so I will go ahead and take a look at merging this today.

**Comment by bhelx** [comment]
@mattcarrier that's always good to know. Thanks for reporting!

**Comment by bhelx** [comment]
👍

**Comment by bhelx** [comment]
Okay I don't think we needed to change all the xml examples anymore. But this is okay and will at least protect us from accidentally reversing this change. Thanks so much @lc-ikrumov !

**Comment by lc-ikrumov** [comment]
@bhelx No problem, thank you for looking into this and verifying the solution.

**Pull request merged**
