### PR TITLE
Map tax_exempt xml field in Adjustment model class

### PR DESCRIPTION
**Pull request by nhartner**
See https://dev.recurly.com/docs/create-a-charge-or-credit for more information on tax_exempt property for adjustments

### CODE REVIEW

**Comment by bhelx** [comment]
Thank you @nhartner

Travis is failing on forks so I am going to run the tests locally

**Comment by pierre** [comment]
👍

**Comment by bhelx** [comment]
Tests pass locally :+1:

**Comment by bhelx** [comment]
@nhartner Sorry for the delay. Thanks again for contributing!

**Pull request merged**
