### PR TITLE
API version 2.17

### PR DESCRIPTION
**Pull request by aaron-suarez**
This brings us up to API version 2.17. There are no breaking changes.

### CODE REVIEW

**Comment by aaron-suarez** [comment]
@pierre Please feel free to do a Maven release of this version at your leisure

**Comment by pierre** [comment]
@aaron-suarez Could you review https://github.com/killbilling/recurly-java-library/pull/302 first?

**Comment by pierre** [comment]
0.22.0 released. Happy holidays! 🎅

**Comment by aaron-suarez** [comment]
@pierre I notice using the latest release that the user agent is still showing `0.18.0`. It gets this value from the `git.properties` file. Do you have any idea why that might be or what we might be able to do about keeping it more accurate?

**Comment by pierre** [comment]
@aaron-suarez Can you open a new ticket with more details? I couldn't reproduce it with a quick unit test.

**Comment by aaron-suarez** [comment]
I think it was specific to my setup. I reinstalled the latest version from Maven central and the user agent was correct. Sorry about the false alarm.

**Pull request merged**
